# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/causes/overcommit/blob/master/config/default.yml
PreCommit:
  RuboCop:
    enabled: true
    problem_on_unmodified_line: warn
